### PR TITLE
Fix for windsweep and assassin bow combo and preparing for refinery

### PR DESCRIPTION
**Pull request by Lorenzooone**
https://community.gamedex.io/t/assassin-bow-should-cancel-windsweeps-no-follow-up-effect/433

### CODE REVIEW

**Comment by Lorenzooone** [comment]
(Don't ask what happened with the first two commits...)

**Comment by Lorenzooone** [comment]
Some weapons are missing (and some in that .json are/were incomplete) Do you know where the missing data is?

**Comment by YukariTea** [comment]
The data missing from the repo can be seen here: https://kagerochart.com/damage-calc/data

I think only @winsomniak can touch that, so there's nothing that can be done on the repo for issues like #13.

**Comment by Lorenzooone** [comment]
Ok... Then we have to add all the new staves and some weapons (like Hagoita) to the weapons.json since they all have upgrades.
BTW, this should fix the bug you reported here: https://github.com/winsomniak/kagero-calc/issues/21

**Comment by winsomniak** [comment]
Any data you see on kagerochart is included in https://kagerochart.com/damage-calc/data, which is a combination of the data here and the data in my database. It should not be necessary to add any weapons if they don't have any special properties like "char_unique".

**Comment by winsomniak** [comment]
This might be helpful @Lorenzooone since the other simulator already did the data entry: https://github.com/Andu2/FEH-Mass-Simulator/blob/master/json/weapon_refine.json, albeit in another format.

**Comment by winsomniak** [comment]
@Lorenzooone are these changes done and tested? I'm out of town next week, hoping to approve this tomorrow.

**Comment by Lorenzooone** [comment]
They should be all working. I keep putting all this as a pull request because seeing each other's errors is easier than seeing oneself's.
These should be fixed too: https://github.com/winsomniak/kagero-calc/issues/23 https://github.com/winsomniak/kagero-calc/issues/24

**Comment by winsomniak** [comment]
@Lorenzooone would you mind making a short bullet point list with everything you fixed for us, and create a separate branch for any other fixes/additions? Hard for me to keep track of everything as is, I want to make sure we account for everything.

Thanks for all the help!

**Comment by Lorenzooone** [comment]
Yeah, you're right, next time I'll make it the way you asked...
Here are the fixes:
- Assassin Bow + Windsweep
- Fixed bug with Wo Dao and AOE
- Fixed Iotes' Shield's seal
- Fixed Dark Greatsword's properties
- Replaced redundant piece of code with function (easier to edit)
- Preparing for refinery with various properties for weapons
- Added following weapons:
-- Guard Bows
-- Keen tomes
-- Slaying Spears
-- Armorsmashers
-- Slaying Hammers

**Comment by winsomniak** [comment]
Alright, I'm approving this but did not have time to test personally, so the changes are not being deployed to KageroChart today. If anyone finds issues please report them as usual.

**Pull request merged**
