### PR TITLE
Fix Steady Breath & Add various stuff

### PR DESCRIPTION
**Pull request by Lorenzooone**

### CODE REVIEW

**Comment by Lorenzooone** [comment]
(Should fix this too? https://community.gamedex.io/t/vengful-fighter-special-cooldown-charge-bonus-does-not-properly-display/511)

**Comment by Lorenzooone** [comment]
Also fixes https://community.gamedex.io/t/divine-tyrfing-incorrectly-applies-to-dragons/486/2
(In theory)

**Comment by winsomniak** [comment]
Awesome, this is great. I need to test this stuff so it may not get merged tonight, but definitely this week. 

One small request: please try to keep your spacing clean and comment any major additions. 

I have not been entirely consistent myself, but with multiple people contributing it can get chaotic. Probably we should use spaces instead of tab characters in our editor settings, too.

Thanks for your help!

Cheers

**Comment by Lorenzooone** [comment]
I tried following your guidelines for this one...
This should fix a number of errors/skills not working (Fjorm & stuff)

**Comment by Lorenzooone** [comment]
This thing made me think: what happens in game if a unit with desperation (Bridelia as an example) quads Fjorm? Does she get the attack from both the activations of the special or doesn't she?

**Comment by YukariTea** [comment]
You added bonds, but they are already present in the calculator. Bond skills don't automatically give their stats, they have a condition requiring at least one adjacent ally. If you go to the calculator's effects tab, you can set the amount of adjacent allies.

**Comment by Lorenzooone** [comment]
You're right... It's there but it doesn't work for defenders... Let me check why...

**Comment by Lorenzooone** [comment]
Done, it's fixed.

**Pull request merged**
