### PR TITLE
Hardy bearing text printing

### PR DESCRIPTION
**Pull request by Lorenzooone**
https://github.com/winsomniak/kagero-calc/issues/56

Could you please check the HP thing here too... Seems to be broken. Sorry.

### CODE REVIEW

**Comment by Lorenzooone** [comment]
Fixed

**Comment by Lorenzooone** [comment]
(@winsomniak )

**Comment by winsomniak** [comment]
Was this one not initHP? We have some ambiguity here, but if I remember correctly the properties are as follows:

hp - maximum hp
currHP - current hp
initHP - hp at start of battle

**Comment by Lorenzooone** [comment]
If it is so... Then let me make sure everything is okay...

**Comment by winsomniak** [comment]
We should add that to the wiki once you confirm. Save citizens of the future some headaches. Haha

**Pull request merged**
