### PR TITLE
Update summer

### PR DESCRIPTION
**Pull request by Lorenzooone**
Commits explain what is what. Fixed some bugs and changed the design. Remember to include Green Bow's icon, Colorless Breath's icon and to swap the Morgans portraits.

### CODE REVIEW

**Comment by Lorenzooone** [comment]
I can't seem to get Custom units icon working... It stays the same if you change movement type and the same happens on the site. The unit gets properly modified though... Do you have any idea on what might be causing this?

**Comment by winsomniak** [comment]
Custom unit icon as in their avatar?

I think the avatar was always a silhouette for custom units in previous versions. I may not be understanding your question correctly though.

**Comment by Lorenzooone** [comment]
cattura
Changing these ones doesn't change the respective icons, both on this pull request and on the site. (The calc updates fine though)

**Comment by winsomniak** [comment]
Ahh ok, Ill have to look into this. Custom units have a bunch of edge casey
code that I've not changed much since the legacy version.

**Pull request merged**
