### PR TITLE
Fixes various bugs in the Calc regarding Follow-ups

### PR DESCRIPTION
**Pull request by Lorenzooone**
Thanks to YukariTea for the updated seals!

I've rewritten some part of the code. Rewriting it all could be really dangerous (bugs) and tiresome, so I decided to approach it little by little.

This "Little" update focuses on the follow-up logic and tries to fix it while making it smaller.

### CODE REVIEW

**Comment by Lorenzooone** [comment]
(I tried testing it as much as possible)

**Comment by Lorenzooone** [comment]
Should fix https://github.com/winsomniak/kagero-calc/issues/74, https://github.com/winsomniak/kagero-calc/issues/65, https://github.com/winsomniak/kagero-calc/issues/67, https://github.com/winsomniak/kagero-calc/issues/68

**Comment by Lorenzooone** [comment]
Fixed @winsomniak

**Comment by winsomniak** [comment]
This one is large so we should run a beta build. I'll merge and throw it up with discord notice after I get the new heroes up.

As always, thanks for helping @Lorenzooone

**Comment by Lorenzooone** [comment]
I can't do this... It's too much stuff changed at one time...

**Comment by Lorenzooone** [comment]
I'll make a new pull request with all the changes

**Pull request closed without merging**
